[package]
name = "seqrush"
version = "0.3.0"
edition = "2021"
authors = ["Kristopher Kubicki <478212+KristopherKubicki@users.noreply.github.com>"]
description = "Lock-free parallel pangenome graph construction"
repository = "https://github.com/KristopherKubicki/seqrush"
license = "MIT"
keywords = ["bioinformatics", "pangenome", "graph", "alignment", "parallel"]
categories = ["science", "command-line-utilities"]

[lib]
name = "seqrush"
path = "src/lib.rs"

[[bin]]
name = "seqrush"
path = "src/main.rs"


[dependencies]
clap = { version = "4", features = ["derive"], optional = true }

[features]
cli = ["clap"]

[dev-dependencies]
tempfile = "3"
